#!/bin/bash

zmcmd="/opt/zimbra/bin/zmmailbox"
#path='/export8/mdir/1/5/mlopez@manquehue.net/Maildir'
path='/export9/mdir/9/47/jpedreros@gtdinternet.com/Maildir'
user=`echo $path |cut -d / -f6`
userfolder="/var/tmp/$user.folder"

#echo user
find . -maxdepth 10 -type d -name cur | awk '{ print length($0),$0 | "sort -n"}' |awk '{print $2}'  |egrep -v '_' | sed '/^\s*$/d'  |awk -F '/' {'print $2'} | sed 's/\./\//g' | while read line;
# echo $line
do
 	if [ "$line" != "/Sent" ] &&  [ "$line" != "/Spam" ] && [ "$line" != "/Drafts" ] && [ "$line" != "/Junk" ] && [ "$line" != "/Trash" ] && [ "$line" != "cur" ] && [ "$line" != "/sent" ]
	then
	    echo $line
	    echo "cf $line" >> $userfolder
	    #echo "cf" > /tmp/borra 
        fi
done
	#Creando carpetas
	echo "Creating folder"
	$zmcmd -z -m $user < $userfolder

dfolders=('Inbox' 'Sent')

for index in ${dfolders[@]}
do
   echo $index
##Sincronizando Inbox Y Enviados
if [ "$index" = "Inbox" ]
then
   echo "Transferring Inbox messages...." 
     for msg in `ls $path'/'cur/ |sort `
       do
          echo "addMessage "/Inbox" "$path'/cur/'$msg" " >> /var/tmp/$user"_mail_"Inbox
        done
        #cargamos los correos del subdirectorio al zimbra
        $zmcmd -z -m $user < /var/tmp/$user"_mail_"Inbox
        echo "Finished transferring Inbox messages...."
else
    echo "Transferring Sent messages...." 
     for msg in `ls $path/'.Sent Items/cur/' |sort `
       do
   	#echo $msg
          echo "addMessage "/Sent" "$path"/.Sent\ Items/cur/"$msg" " >> /var/tmp/$user"_mail_"Sent
        done
        #cargamos los correos del subdirectorio al zimbra
        #$zmcmd -z -m $user < /var/tmp/$user"_mail_"Sent
        echo "Finished transferring Sent messages...."
fi
done
##Fin sincroniza Inbox y Sent
#
##Migrando data de directorios creados
#echo "Generating datafile from folder"
#while read line
#do
# folder=`echo $line|cut -d " " -f2 | sed 's/^\///'g | sed 's/\//./g' `
# #echo $folder
# ##Sincronizando carpetas
# for msg in `ls $path/.$folder'/'cur` 
#   do
#     if [[ "$folder" != *"."* ]]
#     then
#        echo "addMessage "$folder" "$path/.$folder/cur/$msg" " >> /var/tmp/$user"_mail_"$folder
#     else
# 	folderz=`echo $line| awk {'print $2'} |sed 's/\./\//g'`     
#        #echo $folderz
#        echo "addMessage "$folderz" "$path/.$folder/cur/$msg" " >> /var/tmp/$user"_mail_"$folder
#     fi
#   done
#done < $userfolder
#echo "Finished datafile from subfolder"
#
###Cargando data
#for a in `ls /var/tmp/$user* |grep -v Inbox |grep -v folder| grep -v Sent` 
#  do
#     echo $a
#     echo "Start transferring messages from datafiles"
#     $zmcmd -z -m $user < $a
#     echo "Finished transferring messages from datafiles"
#  done
